/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  BadRequestResponseResponse,
  GetCoinChartResponseSchema,
  GetCoinInfoResponseSchema,
  GetCoinsListResponseSchema,
  GetMultiWalletBalanceResponseSchema,
  GetTransactionsListParams,
  GetTransactionsListResponseSchema,
  UnauthorizedResponseResponse,
} from '../../models';
import { customInstance } from '../../templates/mutator';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Get coin chart
 * @summary Get coin chart
 */
export const getCoinChart = (
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetCoinChartResponseSchema>(
    {
      url: `/api/v1/general/coin-chart/${symbol}/${time}/${limit}`,
      method: 'GET',
    },
    options,
  );
};

export const getGetCoinChartQueryKey = (
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
) => {
  return [`/api/v1/general/coin-chart/${symbol}/${time}/${limit}`] as const;
};

export const getGetCoinChartQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinChart>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCoinChartQueryKey(symbol, time, limit);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoinChart>>> = () =>
    getCoinChart(symbol, time, limit, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!(symbol && time && limit),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoinChart>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoinChartQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoinChart>>
>;
export type GetCoinChartQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetCoinChart<
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinChart>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinChart>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinChart<
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinChart>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinChart>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinChart<
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinChart>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get coin chart
 */

export function useGetCoinChart<
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinChart>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoinChartQueryOptions(
    symbol,
    time,
    limit,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetCoinChartSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinChart>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCoinChartQueryKey(symbol, time, limit);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoinChart>>> = () =>
    getCoinChart(symbol, time, limit, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCoinChart>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoinChartSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoinChart>>
>;
export type GetCoinChartSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetCoinChartSuspense<
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinChart>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinChartSuspense<
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinChart>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinChartSuspense<
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinChart>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get coin chart
 */

export function useGetCoinChartSuspense<
  TData = Awaited<ReturnType<typeof getCoinChart>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  time: '1h' | '1d' | '1w' | '1m' | '1y' | 'all',
  limit: number,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinChart>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoinChartSuspenseQueryOptions(
    symbol,
    time,
    limit,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get coin info
 * @summary Get coin info
 */
export const getCoinInfo = (
  walletId: string,
  symbol: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetCoinInfoResponseSchema>(
    { url: `/api/v1/general/coin-info/${walletId}/${symbol}`, method: 'GET' },
    options,
  );
};

export const getGetCoinInfoQueryKey = (walletId: string, symbol: string) => {
  return [`/api/v1/general/coin-info/${walletId}/${symbol}`] as const;
};

export const getGetCoinInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCoinInfoQueryKey(walletId, symbol);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoinInfo>>> = () =>
    getCoinInfo(walletId, symbol, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!(walletId && symbol),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoinInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoinInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoinInfo>>
>;
export type GetCoinInfoQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetCoinInfo<
  TData = Awaited<ReturnType<typeof getCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  symbol: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinInfo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinInfo>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinInfo<
  TData = Awaited<ReturnType<typeof getCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinInfo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinInfo>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinInfo<
  TData = Awaited<ReturnType<typeof getCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get coin info
 */

export function useGetCoinInfo<
  TData = Awaited<ReturnType<typeof getCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoinInfoQueryOptions(walletId, symbol, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetCoinInfoSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  symbol: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetCoinInfoQueryKey(walletId, symbol);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoinInfo>>> = () =>
    getCoinInfo(walletId, symbol, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCoinInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoinInfoSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoinInfo>>
>;
export type GetCoinInfoSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetCoinInfoSuspense<
  TData = Awaited<ReturnType<typeof getCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  symbol: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinInfoSuspense<
  TData = Awaited<ReturnType<typeof getCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  symbol: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinInfoSuspense<
  TData = Awaited<ReturnType<typeof getCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  symbol: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get coin info
 */

export function useGetCoinInfoSuspense<
  TData = Awaited<ReturnType<typeof getCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  symbol: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoinInfoSuspenseQueryOptions(
    walletId,
    symbol,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get list of coins
 * @summary Get list of coins
 */
export const getCoinsList = (
  walletId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetCoinsListResponseSchema>(
    { url: `/api/v1/general/coins-list/${walletId}`, method: 'GET' },
    options,
  );
};

export const getGetCoinsListQueryKey = (walletId: string) => {
  return [`/api/v1/general/coins-list/${walletId}`] as const;
};

export const getGetCoinsListQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoinsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCoinsListQueryKey(walletId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoinsList>>> = () =>
    getCoinsList(walletId, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!walletId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getCoinsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoinsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoinsList>>
>;
export type GetCoinsListQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetCoinsList<
  TData = Awaited<ReturnType<typeof getCoinsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinsList>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinsList>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinsList<
  TData = Awaited<ReturnType<typeof getCoinsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinsList>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCoinsList>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinsList<
  TData = Awaited<ReturnType<typeof getCoinsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get list of coins
 */

export function useGetCoinsList<
  TData = Awaited<ReturnType<typeof getCoinsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getCoinsList>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoinsListQueryOptions(walletId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetCoinsListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getCoinsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCoinsListQueryKey(walletId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getCoinsList>>> = () =>
    getCoinsList(walletId, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getCoinsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCoinsListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCoinsList>>
>;
export type GetCoinsListSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetCoinsListSuspense<
  TData = Awaited<ReturnType<typeof getCoinsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinsListSuspense<
  TData = Awaited<ReturnType<typeof getCoinsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCoinsListSuspense<
  TData = Awaited<ReturnType<typeof getCoinsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get list of coins
 */

export function useGetCoinsListSuspense<
  TData = Awaited<ReturnType<typeof getCoinsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getCoinsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetCoinsListSuspenseQueryOptions(walletId, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get MultiWallet Balance
 * @summary Get MultiWallet Balance
 */
export const getMultiWalletBalance = (
  walletId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetMultiWalletBalanceResponseSchema>(
    { url: `/api/v1/general/multi-wallet-balance/${walletId}`, method: 'GET' },
    options,
  );
};

export const getGetMultiWalletBalanceQueryKey = (walletId: string) => {
  return [`/api/v1/general/multi-wallet-balance/${walletId}`] as const;
};

export const getGetMultiWalletBalanceQueryOptions = <
  TData = Awaited<ReturnType<typeof getMultiWalletBalance>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMultiWalletBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMultiWalletBalanceQueryKey(walletId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMultiWalletBalance>>
  > = () => getMultiWalletBalance(walletId, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!walletId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getMultiWalletBalance>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMultiWalletBalanceQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMultiWalletBalance>>
>;
export type GetMultiWalletBalanceQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetMultiWalletBalance<
  TData = Awaited<ReturnType<typeof getMultiWalletBalance>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMultiWalletBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMultiWalletBalance>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMultiWalletBalance<
  TData = Awaited<ReturnType<typeof getMultiWalletBalance>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMultiWalletBalance>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMultiWalletBalance>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMultiWalletBalance<
  TData = Awaited<ReturnType<typeof getMultiWalletBalance>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMultiWalletBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get MultiWallet Balance
 */

export function useGetMultiWalletBalance<
  TData = Awaited<ReturnType<typeof getMultiWalletBalance>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getMultiWalletBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMultiWalletBalanceQueryOptions(walletId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetMultiWalletBalanceSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getMultiWalletBalance>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getMultiWalletBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetMultiWalletBalanceQueryKey(walletId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getMultiWalletBalance>>
  > = () => getMultiWalletBalance(walletId, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getMultiWalletBalance>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetMultiWalletBalanceSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getMultiWalletBalance>>
>;
export type GetMultiWalletBalanceSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetMultiWalletBalanceSuspense<
  TData = Awaited<ReturnType<typeof getMultiWalletBalance>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getMultiWalletBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMultiWalletBalanceSuspense<
  TData = Awaited<ReturnType<typeof getMultiWalletBalance>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getMultiWalletBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetMultiWalletBalanceSuspense<
  TData = Awaited<ReturnType<typeof getMultiWalletBalance>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getMultiWalletBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get MultiWallet Balance
 */

export function useGetMultiWalletBalanceSuspense<
  TData = Awaited<ReturnType<typeof getMultiWalletBalance>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getMultiWalletBalance>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetMultiWalletBalanceSuspenseQueryOptions(
    walletId,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get list of transactions
 * @summary Get list of transactions
 */
export const getTransactionsList = (
  walletId: string,
  params?: GetTransactionsListParams,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetTransactionsListResponseSchema>(
    {
      url: `/api/v1/general/transactions-list/${walletId}`,
      method: 'GET',
      params,
    },
    options,
  );
};

export const getGetTransactionsListQueryKey = (
  walletId: string,
  params?: GetTransactionsListParams,
) => {
  return [
    `/api/v1/general/transactions-list/${walletId}`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetTransactionsListQueryOptions = <
  TData = Awaited<ReturnType<typeof getTransactionsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  params?: GetTransactionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTransactionsListQueryKey(walletId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTransactionsList>>
  > = () => getTransactionsList(walletId, params, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!walletId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getTransactionsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTransactionsListQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTransactionsList>>
>;
export type GetTransactionsListQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetTransactionsList<
  TData = Awaited<ReturnType<typeof getTransactionsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  params: undefined | GetTransactionsListParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsList>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsList>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsList<
  TData = Awaited<ReturnType<typeof getTransactionsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  params?: GetTransactionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsList>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTransactionsList>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsList<
  TData = Awaited<ReturnType<typeof getTransactionsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  params?: GetTransactionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get list of transactions
 */

export function useGetTransactionsList<
  TData = Awaited<ReturnType<typeof getTransactionsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  params?: GetTransactionsListParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTransactionsListQueryOptions(
    walletId,
    params,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetTransactionsListSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getTransactionsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  params?: GetTransactionsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTransactionsListQueryKey(walletId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getTransactionsList>>
  > = () => getTransactionsList(walletId, params, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getTransactionsList>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetTransactionsListSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTransactionsList>>
>;
export type GetTransactionsListSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetTransactionsListSuspense<
  TData = Awaited<ReturnType<typeof getTransactionsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  params: undefined | GetTransactionsListParams,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsListSuspense<
  TData = Awaited<ReturnType<typeof getTransactionsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  params?: GetTransactionsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTransactionsListSuspense<
  TData = Awaited<ReturnType<typeof getTransactionsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  params?: GetTransactionsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get list of transactions
 */

export function useGetTransactionsListSuspense<
  TData = Awaited<ReturnType<typeof getTransactionsList>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  params?: GetTransactionsListParams,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getTransactionsList>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTransactionsListSuspenseQueryOptions(
    walletId,
    params,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
