/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

/**
 * Check existence of a MultiWallet
 * @summary Check existence of a MultiWallet
 */
export const postCheckExistenceMultiWalletHeader = zod.object({
  Authorization: zod.string(),
});

export const postCheckExistenceMultiWalletBody = zod.object({
  mnemonic: zod.array(zod.string()),
});

export const postCheckExistenceMultiWalletResponse = zod.object({
  exists: zod.boolean(),
});

/**
 * Create a MultiWallet
 * @summary Create a MultiWallet
 */
export const postCreateMultiWalletHeader = zod.object({
  Authorization: zod.string(),
});

export const postCreateMultiWalletBody = zod.object({
  name: zod.string().nullish(),
  pin: zod.string(),
  ref_code: zod.string().nullish(),
});

export const postCreateMultiWalletResponse = zod.object({
  id: zod.string().uuid(),
  mnemonic: zod.array(zod.string()),
  mnemonic_hash: zod.string(),
  name: zod.string(),
});

/**
 * Export a MultiWallet
 * @summary Export a MultiWallet
 */
export const postExportMultiWalletHeader = zod.object({
  Authorization: zod.string(),
});

export const postExportMultiWalletBody = zod.object({
  id: zod.string().uuid(),
  mnemonic_hash: zod.string(),
  pin: zod.string(),
});

export const postExportMultiWalletResponse = zod.object({
  mnemonic: zod.array(zod.string()),
});

/**
 * Import a MultiWallet
 * @summary Import a MultiWallet
 */
export const postImportMultiWalletHeader = zod.object({
  Authorization: zod.string(),
});

export const postImportMultiWalletBody = zod.object({
  mnemonic: zod.array(zod.string()),
  name: zod.string().nullish(),
  pin: zod.string(),
  ref_code: zod.string().nullish(),
});

export const postImportMultiWalletResponse = zod.object({
  id: zod.string().uuid(),
  mnemonic_hash: zod.string(),
  name: zod.string(),
});

/**
 * List all MultiWallets
 * @summary List MultiWallets
 */
export const postListMultiWalletsHeader = zod.object({
  Authorization: zod.string(),
});

export const postListMultiWalletsBody = zod.object({
  ids: zod.array(zod.string().uuid()),
});

export const postListMultiWalletsResponseItem = zod.object({
  balance: zod.number(),
  id: zod.string().uuid(),
  name: zod.string(),
  pnl: zod.number(),
  roi: zod.number(),
});
export const postListMultiWalletsResponse = zod.array(
  postListMultiWalletsResponseItem,
);

/**
 * Update a MultiWallet's name
 * @summary Update a MultiWallet
 */
export const postUpdateMultiWalletHeader = zod.object({
  Authorization: zod.string(),
});

export const postUpdateMultiWalletBody = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
});

export const postUpdateMultiWalletResponse = zod.object({
  id: zod.string().uuid(),
  name: zod.string(),
});
