/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

/**
 * Get transaction fee
 * @summary Get transaction fee
 */
export const getFeeParams = zod.object({
  symbol: zod.string(),
  network: zod.enum([
    'ethereum',
    'bsc',
    'polygon',
    'solana',
    'tron',
    'bitcoin',
  ]),
});

export const getFeeHeader = zod.object({
  Authorization: zod.string(),
});

export const getFeeResponse = zod.object({
  fee: zod.number(),
});

/**
 * Receive transaction to address
 * @summary Receive transaction to address
 */
export const postReceiveHeader = zod.object({
  Authorization: zod.string(),
});

export const postReceiveBody = zod.object({
  network: zod.enum([
    'ethereum',
    'bsc',
    'polygon',
    'solana',
    'tron',
    'bitcoin',
  ]),
  symbol: zod.string(),
  walletId: zod.string().uuid(),
});

export const postReceiveResponse = zod.object({
  address: zod.string(),
});

/**
 * Send transaction to address
 * @summary Send transaction to address
 */
export const postSendHeader = zod.object({
  Authorization: zod.string(),
});

export const postSendBody = zod.object({
  address: zod.string(),
  amount: zod.number(),
  network: zod.enum([
    'ethereum',
    'bsc',
    'polygon',
    'solana',
    'tron',
    'bitcoin',
  ]),
  symbol: zod.string(),
  walletId: zod.string().uuid(),
});

export const postSendResponse = zod.object({
  status: zod.enum(['pending', 'success', 'failed']),
  transactionId: zod.string().uuid(),
});

/**
 * Create swap
 * @summary Create swap
 */
export const postSwapHeader = zod.object({
  Authorization: zod.string(),
});

export const postSwapBody = zod.object({
  receive: zod.object({
    network: zod.enum([
      'ethereum',
      'bsc',
      'polygon',
      'solana',
      'tron',
      'bitcoin',
    ]),
    symbol: zod.string(),
  }),
  send: zod.object({
    amount: zod.number(),
    network: zod.enum([
      'ethereum',
      'bsc',
      'polygon',
      'solana',
      'tron',
      'bitcoin',
    ]),
    symbol: zod.string(),
  }),
  walletId: zod.string().uuid(),
});

export const postSwapResponse = zod.object({
  status: zod.enum(['pending', 'success', 'failed']),
  swapId: zod.string().uuid(),
});
