/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

/**
 * Authorize a device to obtain a JWT token which grants access to the APIs for user
 * @summary Authorize a device
 */
export const postAuthorizeDeviceBody = zod.object({
  device_id: zod.string(),
  device_ip: zod.string(),
  device_name: zod.string(),
  device_os: zod.string(),
});

export const postAuthorizeDeviceResponse = zod.object({
  id: zod.string().uuid(),
  token: zod.string(),
});

/**
 * @summary List devices. TESTING PURPOSES ONLY, NOT FOR PRODUCTION USE
 */
export const listDevicesEndpointResponseItem = zod.object({
  created_at: zod.string().datetime(),
  device_id: zod.string(),
  device_ip: zod.string(),
  device_name: zod.string(),
  device_os: zod.string(),
  id: zod.string().uuid(),
  updated_at: zod.string().datetime(),
});
export const listDevicesEndpointResponse = zod.array(
  listDevicesEndpointResponseItem,
);

/**
 * Re-authorize a device to obtain a new JWT token, and update the device details. Previous token will be invalidated.
 * @summary Update a device
 */
export const postUpdateDeviceHeader = zod.object({
  Authorization: zod.string(),
});

export const postUpdateDeviceBody = zod.object({
  device_id: zod.string().nullish(),
  device_ip: zod.string().nullish(),
  device_name: zod.string().nullish(),
  device_os: zod.string().nullish(),
  id: zod.string().uuid(),
});

export const postUpdateDeviceResponse = zod.object({
  created_at: zod.string().datetime(),
  device_id: zod.string(),
  device_ip: zod.string(),
  device_name: zod.string(),
  device_os: zod.string(),
  id: zod.string().uuid(),
  updated_at: zod.string().datetime(),
});
