/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

/**
 * Get available staking coins
 * @summary Get available staking coins
 */
export const getAvailableStakingCoinsHeader = zod.object({
  Authorization: zod.string(),
});

export const getAvailableStakingCoinsResponse = zod.object({
  coins: zod.array(
    zod.object({
      aprFrom: zod.number(),
      aprTo: zod.number(),
      icon: zod.string(),
      name: zod.string(),
      symbol: zod.string(),
    }),
  ),
});

/**
 * Stake
 * @summary Stake
 */
export const postStakeHeader = zod.object({
  Authorization: zod.string(),
});

export const postStakeBody = zod.object({
  amount: zod.number(),
  stakingId: zod.string().uuid(),
  walletId: zod.string().uuid(),
});

export const postStakeResponse = zod.object({
  stakingId: zod.string().uuid(),
});

/**
 * Get staking
 * @summary Get staking
 */
export const getStakingParams = zod.object({
  walletId: zod.string().uuid(),
  stakingId: zod.string().uuid(),
});

export const getStakingHeader = zod.object({
  Authorization: zod.string(),
});

export const getStakingResponse = zod.object({
  apr: zod.number(),
  currentValue: zod.number(),
  icon: zod.string(),
  name: zod.string(),
  period: zod.array(zod.number()),
  stakingId: zod.string().uuid(),
  startValue: zod.number(),
  status: zod.enum(['staking', 'unstaking', 'finished']),
  symbol: zod.string(),
});

/**
 * Get staking accruals
 * @summary Get staking accruals
 */
export const getStakingAccrualsParams = zod.object({
  walletId: zod.string().uuid(),
  stakingId: zod.string().uuid(),
});

export const getStakingAccrualsHeader = zod.object({
  Authorization: zod.string(),
});

export const getStakingAccrualsResponse = zod.object({
  listOfAccruals: zod.array(
    zod.object({
      amount: zod.number(),
      date: zod.number(),
      icon: zod.string(),
      symbol: zod.string(),
    }),
  ),
});

/**
 * Get staking coin info
 * @summary Get staking coin info
 */
export const getStakingCoinInfoParams = zod.object({
  symbol: zod.string(),
});

export const getStakingCoinInfoHeader = zod.object({
  Authorization: zod.string(),
});

export const getStakingCoinInfoResponse = zod.object({
  icon: zod.string(),
  name: zod.string(),
  opportunities: zod.array(
    zod.object({
      apr: zod.number(),
      maxAmountPerOrder: zod.number(),
      minAmountPerOrder: zod.number(),
      network: zod.enum([
        'ethereum',
        'bsc',
        'polygon',
        'solana',
        'tron',
        'bitcoin',
      ]),
      stakingId: zod.string().uuid(),
      timeTillUnstake: zod.number(),
      timeTillUnstakeAvailable: zod.number().nullish(),
    }),
  ),
  symbol: zod.string(),
});

/**
 * Get staking history
 * @summary Get staking history
 */
export const getStakingHistoryParams = zod.object({
  walletId: zod.string().uuid(),
});

export const getStakingHistoryHeader = zod.object({
  Authorization: zod.string(),
});

export const getStakingHistoryResponse = zod.object({
  history: zod.array(
    zod.object({
      amount: zod.number(),
      apr: zod.number(),
      icon: zod.string(),
      name: zod.string(),
      network: zod.enum([
        'ethereum',
        'bsc',
        'polygon',
        'solana',
        'tron',
        'bitcoin',
      ]),
      period: zod.array(zod.number()),
      stakingId: zod.string().uuid(),
      symbol: zod.string(),
    }),
  ),
});

/**
 * Get staking information
 * @summary Get staking information
 */
export const getStakingInfoParams = zod.object({
  walletId: zod.string().uuid(),
});

export const getStakingInfoHeader = zod.object({
  Authorization: zod.string(),
});

export const getStakingInfoBody = zod.object({
  amount: zod.number(),
  stakingId: zod.string().uuid(),
  walletId: zod.string().uuid(),
});

export const getStakingInfoResponse = zod.object({
  balance: zod.object({
    middleApr: zod.number(),
    value: zod.number(),
  }),
  listOfStaking: zod.array(
    zod.object({
      apr: zod.number(),
      currentValue: zod.number(),
      icon: zod.string(),
      network: zod.enum([
        'ethereum',
        'bsc',
        'polygon',
        'solana',
        'tron',
        'bitcoin',
      ]),
      stakingId: zod.string().uuid(),
      status: zod.enum(['staking', 'unstaking', 'finished']),
      symbol: zod.string(),
    }),
  ),
});

/**
 * Unstake
 * @summary Unstake
 */
export const postUnstakeHeader = zod.object({
  Authorization: zod.string(),
});

export const postUnstakeBody = zod.object({
  amount: zod.number(),
  stakingId: zod.string().uuid(),
  walletId: zod.string().uuid(),
});

export const postUnstakeResponse = zod.object({
  stakingId: zod.string().uuid(),
  status: zod.enum(['unstaking', 'rejected', 'finished']),
});
