/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

/**
 * Get Referral Screen
 * @summary Get Referral Screen
 */
export const getReferralScreenParams = zod.object({
  walletId: zod.string().uuid(),
});

export const getReferralScreenHeader = zod.object({
  Authorization: zod.string(),
});

export const getReferralScreenResponse = zod.object({
  listOfAccruals: zod.array(
    zod.object({
      date: zod.number(),
      icon: zod.string(),
      name: zod.string(),
      symbol: zod.string(),
      value: zod.number(),
    }),
  ),
  referralLink: zod.string(),
});
