/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery,
  useSuspenseQuery
} from '@tanstack/react-query'
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult
} from '@tanstack/react-query'
import type {
  BadRequestResponseResponse,
  DeviceAuthResponseSchema,
  DeviceCreateSchema,
  DeviceResponseSchema,
  DeviceUpdateSchema,
  ErrorSchema,
  HttpError,
  UnauthorizedResponseResponse
} from '../../models'
import { customInstance } from '../../templates/mutator';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * Authorize a device to obtain a JWT token which grants access to the APIs for user
 * @summary Authorize a device
 */
export const postAuthorizeDevice = (
    deviceCreateSchema: DeviceCreateSchema,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeviceAuthResponseSchema>(
      {url: `/api/v1/device/authorize`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deviceCreateSchema
    },
      options);
    }
  


export const getPostAuthorizeDeviceMutationOptions = <TData = Awaited<ReturnType<typeof postAuthorizeDevice>>, TError = HttpError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: DeviceCreateSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
const mutationKey = ['postAuthorizeDevice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthorizeDevice>>, {data: DeviceCreateSchema}> = (props) => {
          const {data} = props ?? {};

          return  postAuthorizeDevice(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions } as UseMutationOptions<TData, TError,{data: DeviceCreateSchema}, TContext>}

    export type PostAuthorizeDeviceMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthorizeDevice>>>
    export type PostAuthorizeDeviceMutationBody = DeviceCreateSchema
    export type PostAuthorizeDeviceMutationError = HttpError

    /**
 * @summary Authorize a device
 */
export const usePostAuthorizeDevice = <TData = Awaited<ReturnType<typeof postAuthorizeDevice>>, TError = HttpError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: DeviceCreateSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        TData,
        TError,
        {data: DeviceCreateSchema},
        TContext
      > => {

      const mutationOptions = getPostAuthorizeDeviceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * @summary List devices. TESTING PURPOSES ONLY, NOT FOR PRODUCTION USE
 */
export const listDevicesEndpoint = (
    
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeviceResponseSchema[]>(
      {url: `/api/v1/device/list`, method: 'GET'
    },
      options);
    }
  

export const getListDevicesEndpointQueryKey = () => {
    return [`/api/v1/device/list`] as const;
    }

    
export const getListDevicesEndpointQueryOptions = <TData = Awaited<ReturnType<typeof listDevicesEndpoint>>, TError = ErrorSchema>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDevicesEndpointQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDevicesEndpoint>>> = () => listDevicesEndpoint(requestOptions);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDevicesEndpointQueryResult = NonNullable<Awaited<ReturnType<typeof listDevicesEndpoint>>>
export type ListDevicesEndpointQueryError = ErrorSchema


export function useListDevicesEndpoint<TData = Awaited<ReturnType<typeof listDevicesEndpoint>>, TError = ErrorSchema>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDevicesEndpoint>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDevicesEndpoint<TData = Awaited<ReturnType<typeof listDevicesEndpoint>>, TError = ErrorSchema>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDevicesEndpoint>>,
          TError,
          TData
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDevicesEndpoint<TData = Awaited<ReturnType<typeof listDevicesEndpoint>>, TError = ErrorSchema>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List devices. TESTING PURPOSES ONLY, NOT FOR PRODUCTION USE
 */

export function useListDevicesEndpoint<TData = Awaited<ReturnType<typeof listDevicesEndpoint>>, TError = ErrorSchema>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDevicesEndpointQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getListDevicesEndpointSuspenseQueryOptions = <TData = Awaited<ReturnType<typeof listDevicesEndpoint>>, TError = ErrorSchema>( options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDevicesEndpointQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDevicesEndpoint>>> = () => listDevicesEndpoint(requestOptions);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseSuspenseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDevicesEndpointSuspenseQueryResult = NonNullable<Awaited<ReturnType<typeof listDevicesEndpoint>>>
export type ListDevicesEndpointSuspenseQueryError = ErrorSchema


export function useListDevicesEndpointSuspense<TData = Awaited<ReturnType<typeof listDevicesEndpoint>>, TError = ErrorSchema>(
  options: { query:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDevicesEndpointSuspense<TData = Awaited<ReturnType<typeof listDevicesEndpoint>>, TError = ErrorSchema>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDevicesEndpointSuspense<TData = Awaited<ReturnType<typeof listDevicesEndpoint>>, TError = ErrorSchema>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List devices. TESTING PURPOSES ONLY, NOT FOR PRODUCTION USE
 */

export function useListDevicesEndpointSuspense<TData = Awaited<ReturnType<typeof listDevicesEndpoint>>, TError = ErrorSchema>(
  options?: { query?:Partial<UseSuspenseQueryOptions<Awaited<ReturnType<typeof listDevicesEndpoint>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}

  ):  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDevicesEndpointSuspenseQueryOptions(options)

  const query = useSuspenseQuery(queryOptions) as  UseSuspenseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * Re-authorize a device to obtain a new JWT token, and update the device details. Previous token will be invalidated.
 * @summary Update a device
 */
export const postUpdateDevice = (
    deviceUpdateSchema: DeviceUpdateSchema,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<DeviceResponseSchema>(
      {url: `/api/v1/device/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deviceUpdateSchema
    },
      options);
    }
  


export const getPostUpdateDeviceMutationOptions = <TData = Awaited<ReturnType<typeof postUpdateDevice>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: DeviceUpdateSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
const mutationKey = ['postUpdateDevice'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUpdateDevice>>, {data: DeviceUpdateSchema}> = (props) => {
          const {data} = props ?? {};

          return  postUpdateDevice(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions } as UseMutationOptions<TData, TError,{data: DeviceUpdateSchema}, TContext>}

    export type PostUpdateDeviceMutationResult = NonNullable<Awaited<ReturnType<typeof postUpdateDevice>>>
    export type PostUpdateDeviceMutationBody = DeviceUpdateSchema
    export type PostUpdateDeviceMutationError = BadRequestResponseResponse | UnauthorizedResponseResponse

    /**
 * @summary Update a device
 */
export const usePostUpdateDevice = <TData = Awaited<ReturnType<typeof postUpdateDevice>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: DeviceUpdateSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        TData,
        TError,
        {data: DeviceUpdateSchema},
        TContext
      > => {

      const mutationOptions = getPostUpdateDeviceMutationOptions(options);

      return useMutation(mutationOptions);
    }
    