/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod';

/**
 * Get coin chart
 * @summary Get coin chart
 */
export const getCoinChartPathLimitMax = 100;

export const getCoinChartParams = zod.object({
  symbol: zod.string(),
  time: zod.enum(['1h', '1d', '1w', '1m', '1y', 'all']),
  limit: zod.number().min(1).max(getCoinChartPathLimitMax),
});

export const getCoinChartHeader = zod.object({
  Authorization: zod.string(),
});

export const getCoinChartResponse = zod.object({
  chart: zod.array(zod.number()),
});

/**
 * Get coin info
 * @summary Get coin info
 */
export const getCoinInfoParams = zod.object({
  walletId: zod.string().uuid(),
  symbol: zod.string(),
});

export const getCoinInfoHeader = zod.object({
  Authorization: zod.string(),
});

export const getCoinInfoResponse = zod.object({
  balance: zod.object({
    pnl: zod.number(),
    price: zod.number(),
    roi: zod.number(),
    value: zod.number(),
  }),
  icon: zod.string(),
  name: zod.string(),
  networksBalances: zod.array(
    zod.object({
      network: zod.enum([
        'ethereum',
        'bsc',
        'polygon',
        'solana',
        'tron',
        'bitcoin',
      ]),
      value: zod.number(),
    }),
  ),
  symbol: zod.string(),
});

/**
 * Get list of coins
 * @summary Get list of coins
 */
export const getCoinsListParams = zod.object({
  walletId: zod.string().uuid(),
});

export const getCoinsListHeader = zod.object({
  Authorization: zod.string(),
});

export const getCoinsListResponse = zod.object({
  coins: zod.array(
    zod.object({
      icon: zod.string(),
      name: zod.string(),
      pnl: zod.number(),
      price: zod.number(),
      symbol: zod.string(),
      value: zod.number(),
    }),
  ),
});

/**
 * Get MultiWallet Balance
 * @summary Get MultiWallet Balance
 */
export const getMultiWalletBalanceParams = zod.object({
  walletId: zod.string().uuid(),
});

export const getMultiWalletBalanceHeader = zod.object({
  Authorization: zod.string(),
});

export const getMultiWalletBalanceResponse = zod.object({
  pnl: zod.number(),
  roi: zod.number(),
  value: zod.number(),
});

/**
 * Get list of transactions
 * @summary Get list of transactions
 */
export const getTransactionsListParams = zod.object({
  walletId: zod.string().uuid(),
});

export const getTransactionsListQueryParams = zod.object({
  symbol: zod.string().optional(),
});

export const getTransactionsListHeader = zod.object({
  Authorization: zod.string(),
});

export const getTransactionsListResponse = zod.object({
  transactions: zod.array(
    zod.object({
      date: zod.number(),
      receiveCoin: zod
        .null()
        .or(
          zod.object({
            amount: zod.number(),
            icon: zod.string(),
            symbol: zod.string(),
          }),
        )
        .optional(),
      sendCoin: zod
        .null()
        .or(
          zod.object({
            amount: zod.number(),
            fee: zod.number(),
            icon: zod.string(),
            symbol: zod.string(),
          }),
        )
        .optional(),
      status: zod.enum(['pending', 'success', 'failed']),
      stepOfProcedure: zod
        .null()
        .or(zod.enum(['reserving', 'processing', 'wrapping_up', 'finished']))
        .optional(),
      type: zod.enum(['receive', 'send', 'swap']),
    }),
  ),
});
