/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import { useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  BadRequestResponseResponse,
  GetReferralScreenResponseSchema,
  UnauthorizedResponseResponse,
} from '../../models';
import { customInstance } from '../../templates/mutator';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Get Referral Screen
 * @summary Get Referral Screen
 */
export const getReferralScreen = (
  walletId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetReferralScreenResponseSchema>(
    { url: `/api/v1/referral/${walletId}`, method: 'GET' },
    options,
  );
};

export const getGetReferralScreenQueryKey = (walletId: string) => {
  return [`/api/v1/referral/${walletId}`] as const;
};

export const getGetReferralScreenQueryOptions = <
  TData = Awaited<ReturnType<typeof getReferralScreen>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReferralScreen>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetReferralScreenQueryKey(walletId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReferralScreen>>
  > = () => getReferralScreen(walletId, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!walletId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getReferralScreen>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReferralScreenQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReferralScreen>>
>;
export type GetReferralScreenQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetReferralScreen<
  TData = Awaited<ReturnType<typeof getReferralScreen>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReferralScreen>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferralScreen>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReferralScreen<
  TData = Awaited<ReturnType<typeof getReferralScreen>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReferralScreen>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReferralScreen>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReferralScreen<
  TData = Awaited<ReturnType<typeof getReferralScreen>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReferralScreen>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Referral Screen
 */

export function useGetReferralScreen<
  TData = Awaited<ReturnType<typeof getReferralScreen>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getReferralScreen>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReferralScreenQueryOptions(walletId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetReferralScreenSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getReferralScreen>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReferralScreen>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetReferralScreenQueryKey(walletId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getReferralScreen>>
  > = () => getReferralScreen(walletId, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getReferralScreen>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReferralScreenSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getReferralScreen>>
>;
export type GetReferralScreenSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetReferralScreenSuspense<
  TData = Awaited<ReturnType<typeof getReferralScreen>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReferralScreen>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReferralScreenSuspense<
  TData = Awaited<ReturnType<typeof getReferralScreen>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReferralScreen>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReferralScreenSuspense<
  TData = Awaited<ReturnType<typeof getReferralScreen>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReferralScreen>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Referral Screen
 */

export function useGetReferralScreenSuspense<
  TData = Awaited<ReturnType<typeof getReferralScreen>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getReferralScreen>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetReferralScreenSuspenseQueryOptions(
    walletId,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
