/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  BadRequestResponseResponse,
  FeeResponseSchema,
  Network,
  ReceiveResponseSchema,
  ReceiveSchema,
  SendResponseSchema,
  SendSchema,
  SwapResponseSchema,
  SwapSchema,
  UnauthorizedResponseResponse,
} from '../../models';
import { customInstance } from '../../templates/mutator';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Get transaction fee
 * @summary Get transaction fee
 */
export const getFee = (
  symbol: string,
  network: Network,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<FeeResponseSchema>(
    { url: `/api/v1/transact/fee/${symbol}/${network}`, method: 'GET' },
    options,
  );
};

export const getGetFeeQueryKey = (symbol: string, network: Network) => {
  return [`/api/v1/transact/fee/${symbol}/${network}`] as const;
};

export const getGetFeeQueryOptions = <
  TData = Awaited<ReturnType<typeof getFee>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  network: Network,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFeeQueryKey(symbol, network);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFee>>> = () =>
    getFee(symbol, network, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!(symbol && network),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetFeeQueryResult = NonNullable<Awaited<ReturnType<typeof getFee>>>;
export type GetFeeQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetFee<
  TData = Awaited<ReturnType<typeof getFee>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  network: Network,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFee>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFee<
  TData = Awaited<ReturnType<typeof getFee>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  network: Network,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFee>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFee<
  TData = Awaited<ReturnType<typeof getFee>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  network: Network,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get transaction fee
 */

export function useGetFee<
  TData = Awaited<ReturnType<typeof getFee>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  network: Network,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFeeQueryOptions(symbol, network, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetFeeSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getFee>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  network: Network,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetFeeQueryKey(symbol, network);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getFee>>> = () =>
    getFee(symbol, network, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getFee>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetFeeSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getFee>>
>;
export type GetFeeSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetFeeSuspense<
  TData = Awaited<ReturnType<typeof getFee>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  network: Network,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFeeSuspense<
  TData = Awaited<ReturnType<typeof getFee>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  network: Network,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetFeeSuspense<
  TData = Awaited<ReturnType<typeof getFee>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  network: Network,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get transaction fee
 */

export function useGetFeeSuspense<
  TData = Awaited<ReturnType<typeof getFee>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  network: Network,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<Awaited<ReturnType<typeof getFee>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetFeeSuspenseQueryOptions(symbol, network, options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Receive transaction to address
 * @summary Receive transaction to address
 */
export const postReceive = (
  receiveSchema: ReceiveSchema,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<ReceiveResponseSchema>(
    {
      url: `/api/v1/transact/receive`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: receiveSchema,
    },
    options,
  );
};

export const getPostReceiveMutationOptions = <
  TData = Awaited<ReturnType<typeof postReceive>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: ReceiveSchema },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationKey = ['postReceive'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postReceive>>,
    { data: ReceiveSchema }
  > = (props) => {
    const { data } = props ?? {};

    return postReceive(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: ReceiveSchema },
    TContext
  >;
};

export type PostReceiveMutationResult = NonNullable<
  Awaited<ReturnType<typeof postReceive>>
>;
export type PostReceiveMutationBody = ReceiveSchema;
export type PostReceiveMutationError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

/**
 * @summary Receive transaction to address
 */
export const usePostReceive = <
  TData = Awaited<ReturnType<typeof postReceive>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: ReceiveSchema },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<TData, TError, { data: ReceiveSchema }, TContext> => {
  const mutationOptions = getPostReceiveMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Send transaction to address
 * @summary Send transaction to address
 */
export const postSend = (
  sendSchema: SendSchema,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SendResponseSchema>(
    {
      url: `/api/v1/transact/send`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: sendSchema,
    },
    options,
  );
};

export const getPostSendMutationOptions = <
  TData = Awaited<ReturnType<typeof postSend>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { data: SendSchema }, TContext>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationKey = ['postSend'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postSend>>,
    { data: SendSchema }
  > = (props) => {
    const { data } = props ?? {};

    return postSend(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: SendSchema },
    TContext
  >;
};

export type PostSendMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSend>>
>;
export type PostSendMutationBody = SendSchema;
export type PostSendMutationError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

/**
 * @summary Send transaction to address
 */
export const usePostSend = <
  TData = Awaited<ReturnType<typeof postSend>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { data: SendSchema }, TContext>;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<TData, TError, { data: SendSchema }, TContext> => {
  const mutationOptions = getPostSendMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Create swap
 * @summary Create swap
 */
export const postSwap = (
  swapSchema: SwapSchema,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<SwapResponseSchema>(
    {
      url: `/api/v1/transact/swap`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: swapSchema,
    },
    options,
  );
};

export const getPostSwapMutationOptions = <
  TData = Awaited<ReturnType<typeof postSwap>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { data: SwapSchema }, TContext>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationKey = ['postSwap'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postSwap>>,
    { data: SwapSchema }
  > = (props) => {
    const { data } = props ?? {};

    return postSwap(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: SwapSchema },
    TContext
  >;
};

export type PostSwapMutationResult = NonNullable<
  Awaited<ReturnType<typeof postSwap>>
>;
export type PostSwapMutationBody = SwapSchema;
export type PostSwapMutationError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

/**
 * @summary Create swap
 */
export const usePostSwap = <
  TData = Awaited<ReturnType<typeof postSwap>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { data: SwapSchema }, TContext>;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<TData, TError, { data: SwapSchema }, TContext> => {
  const mutationOptions = getPostSwapMutationOptions(options);

  return useMutation(mutationOptions);
};
