/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query'
import type {
  MutationFunction,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query'
import type {
  BadRequestResponseResponse,
  MultiWalletCheckExistenceResponseSchema,
  MultiWalletCheckExistenceSchema,
  MultiWalletCreateResponseSchema,
  MultiWalletCreateSchema,
  MultiWalletExportResponseSchema,
  MultiWalletExportSchema,
  MultiWalletImportResponseSchema,
  MultiWalletImportSchema,
  MultiWalletListResponseSchema,
  MultiWalletListSchema,
  MultiWalletUpdateResponseSchema,
  MultiWalletUpdateSchema,
  UnauthorizedResponseResponse
} from '../../models'
import { customInstance } from '../../templates/mutator';


type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];


/**
 * Check existence of a MultiWallet
 * @summary Check existence of a MultiWallet
 */
export const postCheckExistenceMultiWallet = (
    multiWalletCheckExistenceSchema: MultiWalletCheckExistenceSchema,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<MultiWalletCheckExistenceResponseSchema>(
      {url: `/api/v1/multi_wallet/check`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: multiWalletCheckExistenceSchema
    },
      options);
    }
  


export const getPostCheckExistenceMultiWalletMutationOptions = <TData = Awaited<ReturnType<typeof postCheckExistenceMultiWallet>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletCheckExistenceSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
const mutationKey = ['postCheckExistenceMultiWallet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCheckExistenceMultiWallet>>, {data: MultiWalletCheckExistenceSchema}> = (props) => {
          const {data} = props ?? {};

          return  postCheckExistenceMultiWallet(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions } as UseMutationOptions<TData, TError,{data: MultiWalletCheckExistenceSchema}, TContext>}

    export type PostCheckExistenceMultiWalletMutationResult = NonNullable<Awaited<ReturnType<typeof postCheckExistenceMultiWallet>>>
    export type PostCheckExistenceMultiWalletMutationBody = MultiWalletCheckExistenceSchema
    export type PostCheckExistenceMultiWalletMutationError = BadRequestResponseResponse | UnauthorizedResponseResponse

    /**
 * @summary Check existence of a MultiWallet
 */
export const usePostCheckExistenceMultiWallet = <TData = Awaited<ReturnType<typeof postCheckExistenceMultiWallet>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletCheckExistenceSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        TData,
        TError,
        {data: MultiWalletCheckExistenceSchema},
        TContext
      > => {

      const mutationOptions = getPostCheckExistenceMultiWalletMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Create a MultiWallet
 * @summary Create a MultiWallet
 */
export const postCreateMultiWallet = (
    multiWalletCreateSchema: MultiWalletCreateSchema,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<MultiWalletCreateResponseSchema>(
      {url: `/api/v1/multi_wallet/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: multiWalletCreateSchema
    },
      options);
    }
  


export const getPostCreateMultiWalletMutationOptions = <TData = Awaited<ReturnType<typeof postCreateMultiWallet>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletCreateSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
const mutationKey = ['postCreateMultiWallet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCreateMultiWallet>>, {data: MultiWalletCreateSchema}> = (props) => {
          const {data} = props ?? {};

          return  postCreateMultiWallet(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions } as UseMutationOptions<TData, TError,{data: MultiWalletCreateSchema}, TContext>}

    export type PostCreateMultiWalletMutationResult = NonNullable<Awaited<ReturnType<typeof postCreateMultiWallet>>>
    export type PostCreateMultiWalletMutationBody = MultiWalletCreateSchema
    export type PostCreateMultiWalletMutationError = BadRequestResponseResponse | UnauthorizedResponseResponse

    /**
 * @summary Create a MultiWallet
 */
export const usePostCreateMultiWallet = <TData = Awaited<ReturnType<typeof postCreateMultiWallet>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletCreateSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        TData,
        TError,
        {data: MultiWalletCreateSchema},
        TContext
      > => {

      const mutationOptions = getPostCreateMultiWalletMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Export a MultiWallet
 * @summary Export a MultiWallet
 */
export const postExportMultiWallet = (
    multiWalletExportSchema: MultiWalletExportSchema,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<MultiWalletExportResponseSchema>(
      {url: `/api/v1/multi_wallet/export`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: multiWalletExportSchema
    },
      options);
    }
  


export const getPostExportMultiWalletMutationOptions = <TData = Awaited<ReturnType<typeof postExportMultiWallet>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletExportSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
const mutationKey = ['postExportMultiWallet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postExportMultiWallet>>, {data: MultiWalletExportSchema}> = (props) => {
          const {data} = props ?? {};

          return  postExportMultiWallet(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions } as UseMutationOptions<TData, TError,{data: MultiWalletExportSchema}, TContext>}

    export type PostExportMultiWalletMutationResult = NonNullable<Awaited<ReturnType<typeof postExportMultiWallet>>>
    export type PostExportMultiWalletMutationBody = MultiWalletExportSchema
    export type PostExportMultiWalletMutationError = BadRequestResponseResponse | UnauthorizedResponseResponse

    /**
 * @summary Export a MultiWallet
 */
export const usePostExportMultiWallet = <TData = Awaited<ReturnType<typeof postExportMultiWallet>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletExportSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        TData,
        TError,
        {data: MultiWalletExportSchema},
        TContext
      > => {

      const mutationOptions = getPostExportMultiWalletMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Import a MultiWallet
 * @summary Import a MultiWallet
 */
export const postImportMultiWallet = (
    multiWalletImportSchema: MultiWalletImportSchema,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<MultiWalletImportResponseSchema>(
      {url: `/api/v1/multi_wallet/import`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: multiWalletImportSchema
    },
      options);
    }
  


export const getPostImportMultiWalletMutationOptions = <TData = Awaited<ReturnType<typeof postImportMultiWallet>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletImportSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
const mutationKey = ['postImportMultiWallet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postImportMultiWallet>>, {data: MultiWalletImportSchema}> = (props) => {
          const {data} = props ?? {};

          return  postImportMultiWallet(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions } as UseMutationOptions<TData, TError,{data: MultiWalletImportSchema}, TContext>}

    export type PostImportMultiWalletMutationResult = NonNullable<Awaited<ReturnType<typeof postImportMultiWallet>>>
    export type PostImportMultiWalletMutationBody = MultiWalletImportSchema
    export type PostImportMultiWalletMutationError = BadRequestResponseResponse | UnauthorizedResponseResponse

    /**
 * @summary Import a MultiWallet
 */
export const usePostImportMultiWallet = <TData = Awaited<ReturnType<typeof postImportMultiWallet>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletImportSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        TData,
        TError,
        {data: MultiWalletImportSchema},
        TContext
      > => {

      const mutationOptions = getPostImportMultiWalletMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * List all MultiWallets
 * @summary List MultiWallets
 */
export const postListMultiWallets = (
    multiWalletListSchema: MultiWalletListSchema,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<MultiWalletListResponseSchema[]>(
      {url: `/api/v1/multi_wallet/list`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: multiWalletListSchema
    },
      options);
    }
  


export const getPostListMultiWalletsMutationOptions = <TData = Awaited<ReturnType<typeof postListMultiWallets>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletListSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
const mutationKey = ['postListMultiWallets'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postListMultiWallets>>, {data: MultiWalletListSchema}> = (props) => {
          const {data} = props ?? {};

          return  postListMultiWallets(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions } as UseMutationOptions<TData, TError,{data: MultiWalletListSchema}, TContext>}

    export type PostListMultiWalletsMutationResult = NonNullable<Awaited<ReturnType<typeof postListMultiWallets>>>
    export type PostListMultiWalletsMutationBody = MultiWalletListSchema
    export type PostListMultiWalletsMutationError = BadRequestResponseResponse | UnauthorizedResponseResponse

    /**
 * @summary List MultiWallets
 */
export const usePostListMultiWallets = <TData = Awaited<ReturnType<typeof postListMultiWallets>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletListSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        TData,
        TError,
        {data: MultiWalletListSchema},
        TContext
      > => {

      const mutationOptions = getPostListMultiWalletsMutationOptions(options);

      return useMutation(mutationOptions);
    }
    /**
 * Update a MultiWallet's name
 * @summary Update a MultiWallet
 */
export const postUpdateMultiWallet = (
    multiWalletUpdateSchema: MultiWalletUpdateSchema,
 options?: SecondParameter<typeof customInstance>,) => {
      
      
      return customInstance<MultiWalletUpdateResponseSchema>(
      {url: `/api/v1/multi_wallet/update`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: multiWalletUpdateSchema
    },
      options);
    }
  


export const getPostUpdateMultiWalletMutationOptions = <TData = Awaited<ReturnType<typeof postUpdateMultiWallet>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletUpdateSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
) => {
const mutationKey = ['postUpdateMultiWallet'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postUpdateMultiWallet>>, {data: MultiWalletUpdateSchema}> = (props) => {
          const {data} = props ?? {};

          return  postUpdateMultiWallet(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions } as UseMutationOptions<TData, TError,{data: MultiWalletUpdateSchema}, TContext>}

    export type PostUpdateMultiWalletMutationResult = NonNullable<Awaited<ReturnType<typeof postUpdateMultiWallet>>>
    export type PostUpdateMultiWalletMutationBody = MultiWalletUpdateSchema
    export type PostUpdateMultiWalletMutationError = BadRequestResponseResponse | UnauthorizedResponseResponse

    /**
 * @summary Update a MultiWallet
 */
export const usePostUpdateMultiWallet = <TData = Awaited<ReturnType<typeof postUpdateMultiWallet>>, TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<TData, TError,{data: MultiWalletUpdateSchema}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationResult<
        TData,
        TError,
        {data: MultiWalletUpdateSchema},
        TContext
      > => {

      const mutationOptions = getPostUpdateMultiWalletMutationOptions(options);

      return useMutation(mutationOptions);
    }
    