/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery, useSuspenseQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query';
import type {
  BadRequestResponseResponse,
  GetAvailableStakingCoinsResponseSchema,
  GetStakingAccrualsResponseSchema,
  GetStakingCoinInfoResponseSchema,
  GetStakingHistoryResponseSchema,
  GetStakingInfoResponseSchema,
  GetStakingResponseSchema,
  StakeResponseSchema,
  StakeSchema,
  UnauthorizedResponseResponse,
  UnstakeResponseSchema,
  UnstakeSchema,
} from '../../models';
import { customInstance } from '../../templates/mutator';

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1];

/**
 * Get available staking coins
 * @summary Get available staking coins
 */
export const getAvailableStakingCoins = (
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetAvailableStakingCoinsResponseSchema>(
    { url: `/api/v1/staking/available-staking-coins`, method: 'GET' },
    options,
  );
};

export const getGetAvailableStakingCoinsQueryKey = () => {
  return [`/api/v1/staking/available-staking-coins`] as const;
};

export const getGetAvailableStakingCoinsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAvailableStakingCoins>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAvailableStakingCoins>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAvailableStakingCoinsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAvailableStakingCoins>>
  > = () => getAvailableStakingCoins(requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAvailableStakingCoins>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAvailableStakingCoinsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAvailableStakingCoins>>
>;
export type GetAvailableStakingCoinsQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetAvailableStakingCoins<
  TData = Awaited<ReturnType<typeof getAvailableStakingCoins>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(options: {
  query: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAvailableStakingCoins>>,
      TError,
      TData
    >
  > &
    Pick<
      DefinedInitialDataOptions<
        Awaited<ReturnType<typeof getAvailableStakingCoins>>,
        TError,
        TData
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAvailableStakingCoins<
  TData = Awaited<ReturnType<typeof getAvailableStakingCoins>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAvailableStakingCoins>>,
      TError,
      TData
    >
  > &
    Pick<
      UndefinedInitialDataOptions<
        Awaited<ReturnType<typeof getAvailableStakingCoins>>,
        TError,
        TData
      >,
      'initialData'
    >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAvailableStakingCoins<
  TData = Awaited<ReturnType<typeof getAvailableStakingCoins>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAvailableStakingCoins>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get available staking coins
 */

export function useGetAvailableStakingCoins<
  TData = Awaited<ReturnType<typeof getAvailableStakingCoins>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof getAvailableStakingCoins>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAvailableStakingCoinsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetAvailableStakingCoinsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getAvailableStakingCoins>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getAvailableStakingCoins>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetAvailableStakingCoinsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getAvailableStakingCoins>>
  > = () => getAvailableStakingCoins(requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getAvailableStakingCoins>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAvailableStakingCoinsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAvailableStakingCoins>>
>;
export type GetAvailableStakingCoinsSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetAvailableStakingCoinsSuspense<
  TData = Awaited<ReturnType<typeof getAvailableStakingCoins>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(options: {
  query: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getAvailableStakingCoins>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAvailableStakingCoinsSuspense<
  TData = Awaited<ReturnType<typeof getAvailableStakingCoins>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getAvailableStakingCoins>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAvailableStakingCoinsSuspense<
  TData = Awaited<ReturnType<typeof getAvailableStakingCoins>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getAvailableStakingCoins>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get available staking coins
 */

export function useGetAvailableStakingCoinsSuspense<
  TData = Awaited<ReturnType<typeof getAvailableStakingCoins>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(options?: {
  query?: Partial<
    UseSuspenseQueryOptions<
      Awaited<ReturnType<typeof getAvailableStakingCoins>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetAvailableStakingCoinsSuspenseQueryOptions(options);

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Stake
 * @summary Stake
 */
export const postStake = (
  stakeSchema: StakeSchema,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<StakeResponseSchema>(
    {
      url: `/api/v1/staking/stake`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: stakeSchema,
    },
    options,
  );
};

export const getPostStakeMutationOptions = <
  TData = Awaited<ReturnType<typeof postStake>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { data: StakeSchema }, TContext>;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationKey = ['postStake'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postStake>>,
    { data: StakeSchema }
  > = (props) => {
    const { data } = props ?? {};

    return postStake(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: StakeSchema },
    TContext
  >;
};

export type PostStakeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postStake>>
>;
export type PostStakeMutationBody = StakeSchema;
export type PostStakeMutationError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

/**
 * @summary Stake
 */
export const usePostStake = <
  TData = Awaited<ReturnType<typeof postStake>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<TData, TError, { data: StakeSchema }, TContext>;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<TData, TError, { data: StakeSchema }, TContext> => {
  const mutationOptions = getPostStakeMutationOptions(options);

  return useMutation(mutationOptions);
};
/**
 * Get staking
 * @summary Get staking
 */
export const getStaking = (
  walletId: string,
  stakingId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetStakingResponseSchema>(
    { url: `/api/v1/staking/stake/${walletId}/${stakingId}`, method: 'GET' },
    options,
  );
};

export const getGetStakingQueryKey = (walletId: string, stakingId: string) => {
  return [`/api/v1/staking/stake/${walletId}/${stakingId}`] as const;
};

export const getGetStakingQueryOptions = <
  TData = Awaited<ReturnType<typeof getStaking>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStaking>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStakingQueryKey(walletId, stakingId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStaking>>> = () =>
    getStaking(walletId, stakingId, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!(walletId && stakingId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStaking>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStakingQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStaking>>
>;
export type GetStakingQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetStaking<
  TData = Awaited<ReturnType<typeof getStaking>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStaking>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaking>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaking<
  TData = Awaited<ReturnType<typeof getStaking>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStaking>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStaking>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStaking<
  TData = Awaited<ReturnType<typeof getStaking>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStaking>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get staking
 */

export function useGetStaking<
  TData = Awaited<ReturnType<typeof getStaking>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStaking>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStakingQueryOptions(walletId, stakingId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetStakingSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getStaking>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStaking>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStakingQueryKey(walletId, stakingId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getStaking>>> = () =>
    getStaking(walletId, stakingId, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getStaking>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStakingSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStaking>>
>;
export type GetStakingSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetStakingSuspense<
  TData = Awaited<ReturnType<typeof getStaking>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStaking>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingSuspense<
  TData = Awaited<ReturnType<typeof getStaking>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStaking>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingSuspense<
  TData = Awaited<ReturnType<typeof getStaking>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStaking>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get staking
 */

export function useGetStakingSuspense<
  TData = Awaited<ReturnType<typeof getStaking>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStaking>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStakingSuspenseQueryOptions(
    walletId,
    stakingId,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get staking accruals
 * @summary Get staking accruals
 */
export const getStakingAccruals = (
  walletId: string,
  stakingId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetStakingAccrualsResponseSchema>(
    {
      url: `/api/v1/staking/staking-accruals/${walletId}/${stakingId}`,
      method: 'GET',
    },
    options,
  );
};

export const getGetStakingAccrualsQueryKey = (
  walletId: string,
  stakingId: string,
) => {
  return [`/api/v1/staking/staking-accruals/${walletId}/${stakingId}`] as const;
};

export const getGetStakingAccrualsQueryOptions = <
  TData = Awaited<ReturnType<typeof getStakingAccruals>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingAccruals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetStakingAccrualsQueryKey(walletId, stakingId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStakingAccruals>>
  > = () => getStakingAccruals(walletId, stakingId, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!(walletId && stakingId),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStakingAccruals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStakingAccrualsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStakingAccruals>>
>;
export type GetStakingAccrualsQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetStakingAccruals<
  TData = Awaited<ReturnType<typeof getStakingAccruals>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingAccruals>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStakingAccruals>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingAccruals<
  TData = Awaited<ReturnType<typeof getStakingAccruals>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingAccruals>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStakingAccruals>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingAccruals<
  TData = Awaited<ReturnType<typeof getStakingAccruals>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingAccruals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get staking accruals
 */

export function useGetStakingAccruals<
  TData = Awaited<ReturnType<typeof getStakingAccruals>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingAccruals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStakingAccrualsQueryOptions(
    walletId,
    stakingId,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetStakingAccrualsSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getStakingAccruals>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingAccruals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetStakingAccrualsQueryKey(walletId, stakingId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStakingAccruals>>
  > = () => getStakingAccruals(walletId, stakingId, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getStakingAccruals>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStakingAccrualsSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStakingAccruals>>
>;
export type GetStakingAccrualsSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetStakingAccrualsSuspense<
  TData = Awaited<ReturnType<typeof getStakingAccruals>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingAccruals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingAccrualsSuspense<
  TData = Awaited<ReturnType<typeof getStakingAccruals>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingAccruals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingAccrualsSuspense<
  TData = Awaited<ReturnType<typeof getStakingAccruals>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingAccruals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get staking accruals
 */

export function useGetStakingAccrualsSuspense<
  TData = Awaited<ReturnType<typeof getStakingAccruals>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakingId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingAccruals>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStakingAccrualsSuspenseQueryOptions(
    walletId,
    stakingId,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get staking coin info
 * @summary Get staking coin info
 */
export const getStakingCoinInfo = (
  symbol: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetStakingCoinInfoResponseSchema>(
    { url: `/api/v1/staking/staking-coin-info/${symbol}`, method: 'GET' },
    options,
  );
};

export const getGetStakingCoinInfoQueryKey = (symbol: string) => {
  return [`/api/v1/staking/staking-coin-info/${symbol}`] as const;
};

export const getGetStakingCoinInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getStakingCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStakingCoinInfoQueryKey(symbol);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStakingCoinInfo>>
  > = () => getStakingCoinInfo(symbol, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!symbol,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStakingCoinInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStakingCoinInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStakingCoinInfo>>
>;
export type GetStakingCoinInfoQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetStakingCoinInfo<
  TData = Awaited<ReturnType<typeof getStakingCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingCoinInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStakingCoinInfo>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingCoinInfo<
  TData = Awaited<ReturnType<typeof getStakingCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingCoinInfo>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStakingCoinInfo>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingCoinInfo<
  TData = Awaited<ReturnType<typeof getStakingCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get staking coin info
 */

export function useGetStakingCoinInfo<
  TData = Awaited<ReturnType<typeof getStakingCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStakingCoinInfoQueryOptions(symbol, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetStakingCoinInfoSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getStakingCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStakingCoinInfoQueryKey(symbol);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStakingCoinInfo>>
  > = () => getStakingCoinInfo(symbol, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getStakingCoinInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStakingCoinInfoSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStakingCoinInfo>>
>;
export type GetStakingCoinInfoSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetStakingCoinInfoSuspense<
  TData = Awaited<ReturnType<typeof getStakingCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingCoinInfoSuspense<
  TData = Awaited<ReturnType<typeof getStakingCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingCoinInfoSuspense<
  TData = Awaited<ReturnType<typeof getStakingCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get staking coin info
 */

export function useGetStakingCoinInfoSuspense<
  TData = Awaited<ReturnType<typeof getStakingCoinInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  symbol: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingCoinInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStakingCoinInfoSuspenseQueryOptions(
    symbol,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get staking history
 * @summary Get staking history
 */
export const getStakingHistory = (
  walletId: string,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetStakingHistoryResponseSchema>(
    { url: `/api/v1/staking/staking-history/${walletId}`, method: 'GET' },
    options,
  );
};

export const getGetStakingHistoryQueryKey = (walletId: string) => {
  return [`/api/v1/staking/staking-history/${walletId}`] as const;
};

export const getGetStakingHistoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getStakingHistory>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStakingHistoryQueryKey(walletId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStakingHistory>>
  > = () => getStakingHistory(walletId, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!walletId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStakingHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStakingHistoryQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStakingHistory>>
>;
export type GetStakingHistoryQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetStakingHistory<
  TData = Awaited<ReturnType<typeof getStakingHistory>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStakingHistory>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingHistory<
  TData = Awaited<ReturnType<typeof getStakingHistory>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingHistory>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStakingHistory>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingHistory<
  TData = Awaited<ReturnType<typeof getStakingHistory>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get staking history
 */

export function useGetStakingHistory<
  TData = Awaited<ReturnType<typeof getStakingHistory>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getStakingHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStakingHistoryQueryOptions(walletId, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetStakingHistorySuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getStakingHistory>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStakingHistoryQueryKey(walletId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStakingHistory>>
  > = () => getStakingHistory(walletId, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getStakingHistory>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStakingHistorySuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStakingHistory>>
>;
export type GetStakingHistorySuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetStakingHistorySuspense<
  TData = Awaited<ReturnType<typeof getStakingHistory>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingHistorySuspense<
  TData = Awaited<ReturnType<typeof getStakingHistory>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingHistorySuspense<
  TData = Awaited<ReturnType<typeof getStakingHistory>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get staking history
 */

export function useGetStakingHistorySuspense<
  TData = Awaited<ReturnType<typeof getStakingHistory>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingHistory>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStakingHistorySuspenseQueryOptions(
    walletId,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get staking information
 * @summary Get staking information
 */
export const getStakingInfo = (
  walletId: string,
  stakeSchema: StakeSchema,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<GetStakingInfoResponseSchema>(
    {
      url: `/api/v1/staking/staking-info/${walletId}`,
      method: 'GET',
      headers: { 'Content-Type': 'application/json' },
    },
    options,
  );
};

export const getGetStakingInfoQueryKey = (
  walletId: string,
  stakeSchema: StakeSchema,
) => {
  return [`/api/v1/staking/staking-info/${walletId}`, stakeSchema] as const;
};

export const getGetStakingInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getStakingInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakeSchema: StakeSchema,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStakingInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStakingInfoQueryKey(walletId, stakeSchema);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStakingInfo>>
  > = () => getStakingInfo(walletId, stakeSchema, requestOptions);

  return {
    queryKey,
    queryFn,
    enabled: !!walletId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getStakingInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStakingInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStakingInfo>>
>;
export type GetStakingInfoQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetStakingInfo<
  TData = Awaited<ReturnType<typeof getStakingInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakeSchema: StakeSchema,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStakingInfo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStakingInfo>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingInfo<
  TData = Awaited<ReturnType<typeof getStakingInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakeSchema: StakeSchema,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStakingInfo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStakingInfo>>,
          TError,
          TData
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingInfo<
  TData = Awaited<ReturnType<typeof getStakingInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakeSchema: StakeSchema,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStakingInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get staking information
 */

export function useGetStakingInfo<
  TData = Awaited<ReturnType<typeof getStakingInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakeSchema: StakeSchema,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getStakingInfo>>, TError, TData>
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStakingInfoQueryOptions(
    walletId,
    stakeSchema,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}

export const getGetStakingInfoSuspenseQueryOptions = <
  TData = Awaited<ReturnType<typeof getStakingInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakeSchema: StakeSchema,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetStakingInfoQueryKey(walletId, stakeSchema);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getStakingInfo>>
  > = () => getStakingInfo(walletId, stakeSchema, requestOptions);

  return { queryKey, queryFn, ...queryOptions } as UseSuspenseQueryOptions<
    Awaited<ReturnType<typeof getStakingInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetStakingInfoSuspenseQueryResult = NonNullable<
  Awaited<ReturnType<typeof getStakingInfo>>
>;
export type GetStakingInfoSuspenseQueryError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

export function useGetStakingInfoSuspense<
  TData = Awaited<ReturnType<typeof getStakingInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakeSchema: StakeSchema,
  options: {
    query: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingInfoSuspense<
  TData = Awaited<ReturnType<typeof getStakingInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakeSchema: StakeSchema,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetStakingInfoSuspense<
  TData = Awaited<ReturnType<typeof getStakingInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakeSchema: StakeSchema,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get staking information
 */

export function useGetStakingInfoSuspense<
  TData = Awaited<ReturnType<typeof getStakingInfo>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
>(
  walletId: string,
  stakeSchema: StakeSchema,
  options?: {
    query?: Partial<
      UseSuspenseQueryOptions<
        Awaited<ReturnType<typeof getStakingInfo>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
): UseSuspenseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetStakingInfoSuspenseQueryOptions(
    walletId,
    stakeSchema,
    options,
  );

  const query = useSuspenseQuery(queryOptions) as UseSuspenseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Unstake
 * @summary Unstake
 */
export const postUnstake = (
  unstakeSchema: UnstakeSchema,
  options?: SecondParameter<typeof customInstance>,
) => {
  return customInstance<UnstakeResponseSchema>(
    {
      url: `/api/v1/staking/unstake`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: unstakeSchema,
    },
    options,
  );
};

export const getPostUnstakeMutationOptions = <
  TData = Awaited<ReturnType<typeof postUnstake>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: UnstakeSchema },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const mutationKey = ['postUnstake'];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      'mutationKey' in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof postUnstake>>,
    { data: UnstakeSchema }
  > = (props) => {
    const { data } = props ?? {};

    return postUnstake(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions } as UseMutationOptions<
    TData,
    TError,
    { data: UnstakeSchema },
    TContext
  >;
};

export type PostUnstakeMutationResult = NonNullable<
  Awaited<ReturnType<typeof postUnstake>>
>;
export type PostUnstakeMutationBody = UnstakeSchema;
export type PostUnstakeMutationError =
  | BadRequestResponseResponse
  | UnauthorizedResponseResponse;

/**
 * @summary Unstake
 */
export const usePostUnstake = <
  TData = Awaited<ReturnType<typeof postUnstake>>,
  TError = BadRequestResponseResponse | UnauthorizedResponseResponse,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    TData,
    TError,
    { data: UnstakeSchema },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationResult<TData, TError, { data: UnstakeSchema }, TContext> => {
  const mutationOptions = getPostUnstakeMutationOptions(options);

  return useMutation(mutationOptions);
};
