/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { BadRequestResponseResponseMessage } from './badRequestResponseResponseMessage';

export type BadRequestResponseResponse = {
  details?: unknown;
  error: string;
  message?: BadRequestResponseResponseMessage;
};
