/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export interface CoinListNode {
  icon: string;
  name: string;
  pnl: number;
  price: number;
  symbol: string;
  value: number;
}
