/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { DeviceUpdateSchemaDeviceId } from './deviceUpdateSchemaDeviceId';
import type { DeviceUpdateSchemaDeviceIp } from './deviceUpdateSchemaDeviceIp';
import type { DeviceUpdateSchemaDeviceName } from './deviceUpdateSchemaDeviceName';
import type { DeviceUpdateSchemaDeviceOs } from './deviceUpdateSchemaDeviceOs';

export interface DeviceUpdateSchema {
  device_id?: DeviceUpdateSchemaDeviceId;
  device_ip?: DeviceUpdateSchemaDeviceIp;
  device_name?: DeviceUpdateSchemaDeviceName;
  device_os?: DeviceUpdateSchemaDeviceOs;
  id: string;
}
