/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export interface DeviceResponseSchema {
  created_at: string;
  device_id: string;
  device_ip: string;
  device_name: string;
  device_os: string;
  id: string;
  updated_at: string;
}
