/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { CoinBalanceNode } from './coinBalanceNode';
import type { NetworkBalanceNode } from './networkBalanceNode';

export interface GetCoinInfoResponseSchema {
  balance: CoinBalanceNode;
  icon: string;
  name: string;
  networksBalances: NetworkBalanceNode[];
  symbol: string;
}
