/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { ReferralAccrualListNode } from './referralAccrualListNode';

export interface GetReferralScreenResponseSchema {
  listOfAccruals: ReferralAccrualListNode[];
  referralLink: string;
}
