/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { StakingOpportunityNode } from './stakingOpportunityNode';

export interface GetStakingCoinInfoResponseSchema {
  icon: string;
  name: string;
  opportunities: StakingOpportunityNode[];
  symbol: string;
}
