/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { StakingStatus } from './stakingStatus';

export interface GetStakingResponseSchema {
  apr: number;
  currentValue: number;
  icon: string;
  name: string;
  period: number[];
  stakingId: string;
  startValue: number;
  status: StakingStatus;
  symbol: string;
}
