/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { StakingAccrualListNode } from './stakingAccrualListNode';

export interface GetStakingAccrualsResponseSchema {
  listOfAccruals: StakingAccrualListNode[];
}
