/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { HttpErrorOneOf } from './httpErrorOneOf';
import type { HttpErrorOneOfThree } from './httpErrorOneOfThree';

export type HttpError = 'InternalServerError' | 'BadRequest' | HttpErrorOneOf | 'NotFound' | 'InvalidHeader' | 'Conflict' | 'ServiceUnavailable' | 'GatewayTimeout' | HttpErrorOneOfThree;
