/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { MultiWalletImportSchemaName } from './multiWalletImportSchemaName';
import type { MultiWalletImportSchemaRefCode } from './multiWalletImportSchemaRefCode';

export interface MultiWalletImportSchema {
  mnemonic: string[];
  name?: MultiWalletImportSchemaName;
  pin: string;
  ref_code?: MultiWalletImportSchemaRefCode;
}
