/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { MultiWalletCreateSchemaName } from './multiWalletCreateSchemaName';
import type { MultiWalletCreateSchemaRefCode } from './multiWalletCreateSchemaRefCode';

export interface MultiWalletCreateSchema {
  name?: MultiWalletCreateSchemaName;
  pin: string;
  ref_code?: MultiWalletCreateSchemaRefCode;
}
