/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export type Network = (typeof Network)[keyof typeof Network];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Network = {
  ethereum: 'ethereum',
  bsc: 'bsc',
  polygon: 'polygon',
  solana: 'solana',
  tron: 'tron',
  bitcoin: 'bitcoin',
} as const;
