/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export interface ReferralAccrualListNode {
  date: number;
  icon: string;
  name: string;
  symbol: string;
  value: number;
}
