/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionStatus } from './transactionStatus';

export interface SendResponseSchema {
  status: TransactionStatus;
  transactionId: string;
}
