/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Network } from './network';

export interface StakingHistoryNode {
  amount: number;
  apr: number;
  icon: string;
  name: string;
  network: Network;
  period: number[];
  stakingId: string;
  symbol: string;
}
