/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export interface StakingAccrualListNode {
  amount: number;
  date: number;
  icon: string;
  symbol: string;
}
