/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export type StakingStatus = (typeof StakingStatus)[keyof typeof StakingStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StakingStatus = {
  staking: 'staking',
  unstaking: 'unstaking',
  finished: 'finished',
} as const;
