/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Network } from './network';
import type { StakingStatus } from './stakingStatus';

export interface StakingNode {
  apr: number;
  currentValue: number;
  icon: string;
  network: Network;
  stakingId: string;
  status: StakingStatus;
  symbol: string;
}
