/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { Network } from './network';
import type { StakingOpportunityNodeTimeTillUnstakeAvailable } from './stakingOpportunityNodeTimeTillUnstakeAvailable';

export interface StakingOpportunityNode {
  apr: number;
  maxAmountPerOrder: number;
  minAmountPerOrder: number;
  network: Network;
  stakingId: string;
  timeTillUnstake: number;
  timeTillUnstakeAvailable?: StakingOpportunityNodeTimeTillUnstakeAvailable;
}
