/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export type SwapStatus = (typeof SwapStatus)[keyof typeof SwapStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SwapStatus = {
  pending: 'pending',
  success: 'success',
  failed: 'failed',
} as const;
