/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { SwapReceiveNode } from './swapReceiveNode';
import type { SwapSendNode } from './swapSendNode';

export interface SwapSchema {
  receive: SwapReceiveNode;
  send: SwapSendNode;
  walletId: string;
}
