/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionReceivedCoinNode } from './transactionReceivedCoinNode';

export type TransactionNodeReceiveCoin = null | TransactionReceivedCoinNode;
