/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */
import type { TransactionNodeReceiveCoin } from './transactionNodeReceiveCoin';
import type { TransactionNodeSendCoin } from './transactionNodeSendCoin';
import type { TransactionStatus } from './transactionStatus';
import type { TransactionNodeStepOfProcedure } from './transactionNodeStepOfProcedure';
import type { TransactionType } from './transactionType';

export interface TransactionNode {
  date: number;
  receiveCoin?: TransactionNodeReceiveCoin;
  sendCoin?: TransactionNodeSendCoin;
  status: TransactionStatus;
  stepOfProcedure?: TransactionNodeStepOfProcedure;
  type: TransactionType;
}
