/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export type TransactionType = typeof TransactionType[keyof typeof TransactionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionType = {
  receive: 'receive',
  send: 'send',
  swap: 'swap',
} as const;
