/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export type TransactionStep = typeof TransactionStep[keyof typeof TransactionStep];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionStep = {
  reserving: 'reserving',
  processing: 'processing',
  wrapping_up: 'wrapping_up',
  finished: 'finished',
} as const;
