/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export type UnauthorizedReasons = typeof UnauthorizedReasons[keyof typeof UnauthorizedReasons];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UnauthorizedReasons = {
  ForeignToken: 'ForeignToken',
  InvalidToken: 'InvalidToken',
  TokenExpired: 'TokenExpired',
  TokenNotFound: 'TokenNotFound',
  TokenNotProvided: 'TokenNotProvided',
  MissingAuthorizationHeader: 'MissingAuthorizationHeader',
} as const;
