/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * GasWallet Backend
 * OpenAPI spec version: 1.0.0
 */

export type UnstakingStatus =
  (typeof UnstakingStatus)[keyof typeof UnstakingStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UnstakingStatus = {
  unstaking: 'unstaking',
  rejected: 'rejected',
  finished: 'finished',
} as const;
